name = "Endering"
author = "Pablo Peraza"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82f1605d549ae861275ccebb2145c96d782d51c2dae363e1a3dc3d8945189820"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
