name = "Fabric_Modpack"
author = "Piousp"
version = "2024.03.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "027a93f4efc3844305ac07911a2ab73020390af4940addf3d7a9fbea42c74d1c"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
