name = "Fabric_Modpack"
author = "Piousp"
version = "2024.03.06"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0645bf2132a70adaa7672bb72a3615aaead5725221bc818ae0a53c4cdb23203"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
