name = "Money Guys 5 Revival"
author = "Piousp"
version = "2024.06.01"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b43c58b8fe59825f8458f21af235430c7e09b157ae3fd432252e7a067f48cfb3"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
