name = "Fabric_Modpack"
author = "Piousp"
version = "2024.03.06"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96bcf308282e2d8b8aba0a4ba95a6a80afb10c525d7edcd9eb3372a27ebda0c0"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
