name = "Fabric_Modpack"
author = "Piousp"
version = "2023.12.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85ed9f7683c695db34373e430bd830fa419d37b4a557229d3f4d91acedbc0712"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
