name = "Money Guys Reborn"
author = "Piousp"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9d08dd468c49929990aed9973c8d74755aa13afa5e2c0702aa7fb1d22eb1bdf"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
