name = "Endering"
author = "Pablo Peraza"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bbf999f4347c8eac4a423d0bfd8479eb3c4dcd3c6fa61450c7430799d7dee13"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
