name = "Fabric_Modpack"
author = "Pablo Peraza"
version = "2023.11.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3581818c86d873d064fb1957da1478b4b1bb8b13c0d273bef71a78706681d17f"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
