name = "Fabric_Modpack"
author = "Pablo Peraza"
version = "2023.11.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1945b14af5c9ee850f7d807b022245716eb8eb638ee3c243f9309eba53b9687"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
