name = "Money Guys 5 Revival"
author = "Piousp"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80715656c7a80ec0a41f288807ec86dbfb1978259e10fbfad1f35ba5bd3ed571"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
