name = "Fabric_Modpack"
author = "Piousp"
version = "2024.03.07"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e1042c0d25db00dc8ebf683a451542d15e3bbbab63420d9d2bd385083bb6bd6"

[versions]
fabric = "0.15.0"
minecraft = "1.20.1"
