name = "Fabric_Modpack"
author = "Pablo Peraza"
version = "2023.11.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab6fe6f938f6b39a5ee776ebe4cb9c03ac3e4e52645ab44b09676eea0b8cb567"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
