name: Generate mrpack

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  generate-mrpack:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v23
      - name: Export modpack name
        run: |
          PACK_NAME=$(nix develop .#builder --command yq '.name' pack.toml)
          echo "PACK_NAME_VERSION=${PACK_NAME}-${{ github.ref_name }}.mrpack" >> $GITHUB_ENV
      - name: Create mrpack
        run: nix develop .#builder --command packwiz modrinth export --output $PACK_NAME_VERSION
      - name: Upload mrpack
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.PACK_NAME_VERSION }}
