name: Generate mrpack

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  generate-mrpack:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v23
      - name: Enter nix develop
        uses: nicknovitski/nix-develop@v1
        with:
          arguments: ./dev#builder
      - name: Export modpack name
        run: |
          PACK_NAME=$(yq '.name' ${{ github.workspace }}/pack.toml)
          echo "PACK_NAME_VERSION=${PACK_NAME}-${{ github.ref_name }}.mrpack" >> $GITHUB_ENV
      - name: Create mrpack
        run: packwiz modrinth export --pack-file ${{ github.workspace }}/pack.toml --output ${{ github.workspace }}/$PACK_NAME_VERSION
      - name: Upload mrpack
        uses: softprops/action-gh-release@v1
        with:
          files: "${{ github.workspace }}/${{ env.PACK_NAME_VERSION }}"
